CREATE TABLE AUTHOR (
  id BIGINT NOT NULL AUTO_INCREMENT(0,1) PRIMARY KEY,
stageName VARCHAR(100),
name VARCHAR(100),
birthday VARCHAR(100),
country VARCHAR(100),
genre VARCHAR(100)
);

CREATE TABLE SONG (
  id BIGINT NOT NULL AUTO_INCREMENT(0,1) PRIMARY KEY,
name VARCHAR(100),
timeline VARCHAR(100),
createdYear VARCHAR(100)
);

CREATE TABLE ALBUM (
  id BIGINT NOT NULL AUTO_INCREMENT(0,1) PRIMARY KEY,
name VARCHAR(100),
releaseDate VARCHAR(100),
isSingleAlbum BOOLEAN,
isDigest BOOLEAN,
genre VARCHAR(100)
);

CREATE TABLE AUTHOR_SONG(
  author_id BIGINT REFERENCES AUTHOR (id),
song_id BIGINT REFERENCES SONG(id)
);

CREATE TABLE SONG_ALBUM(
  song_id BIGINT REFERENCES SONG (id),
album_id BIGINT REFERENCES ALBUM(id)
);